schema_version = "1.0.0"

id = "matbatchtools"
version = "1.3.2"
name = "Material Batch Tools"
tagline = "Quick batch automation of common material tasks"
maintainer = "Theanine3D <theanine3d@gmail.com>"

type = "add-on"

website = "https://github.com/theanine3D/mat-batch-tools"

tags = ["Material", "Node"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

copyright = ["2024 Pedro Valencia"]